apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    version: v1
    group: networking.k8s.io
    kind: Ingress
    name: guestbook
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: guestbook-dev.demo.akuity.io
    - op: replace
      path: /spec/tls/0/hosts/0
      value: guestbook-dev.demo.akuity.io
# - target:
#     version: v1
#     group: apps
#     kind: Deployment
#     name: guestbook
#   patch: |-
#     - op: replace
#       path: /metadata/annotations/argocd.argoproj.io~1hook
#       value: PostSync
